package com.ziffow.edeals.model.user;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user
     *
     * @mbggenerated Sun Dec 07 20:48:00 PST 2014
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Sun Dec 07 20:48:00 PST 2014
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user
     *
     * @return the value of user.user
     *
     * @mbggenerated Sun Dec 07 20:48:00 PST 2014
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user
     *
     * @param user the value for user.user
     *
     * @mbggenerated Sun Dec 07 20:48:00 PST 2014
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Sun Dec 07 20:48:00 PST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Sun Dec 07 20:48:00 PST 2014
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}